POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFndXNfMDAxQGV4YW1wbGUuY29tIiwiZXhwaXJhdGlvbiI6MTc0MDE4NjI4OSwidXNlcklkIjoxfQ.o5qrK9gVJoQlH7pkco-PLT4hMRMtp4C7ixjS64kyOt8

{
    "name": "Agustín",
    "description": "A test event",
    "location": "A test location",
    "datetime": "2025-01-01T15:30:00.000Z"
}