POST http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFndXNfMDAyQGV4YW1wbGUuY29tIiwiZXhwaXJhdGlvbiI6MTc0MDE4NjQzMCwidXNlcklkIjoyfQ.m64e8aD49ekydI8Dup7qi97wl3KHS6vyD4Mxuxv_qMs