PUT http://localhost:8080/events/1
Content-Type: application/json

{
    "name": "Agustín Ezequiel",
    "description": "A real event",
    "location": "In a real location",
    "datetime": "2025-01-01T15:30:00.000Z"
}