POST http://localhost:8080/events
Content-Type: application/json

{
    "name": "Ezequiel",
    "description": "Another test event",
    "location": "In another test location",
    "datetime": "2025-01-01T15:30:00.000Z"
}